services:
  printer-dashboard:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: printer-dashboard
    ports:
      - "2026:2026"
    env_file:
      - .env
    # Necesario para que el contenedor acceda a la red local para SNMP
    # network_mode: host
    volumes:
      - ./app/printers.sqlite3:/app/printers.sqlite3
    restart: always
